apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: safaricom-data-nginx-pvc
  namespace: default
  labels:
    app: safaricom-nginx-app
spec:
  storageClassName: rook-ceph-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
