apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: safaricom-nginx-sts
  namespace: default
spec:
  serviceName: safaricom-nginx-svc
  replicas: 1
  selector:
    matchLabels:
      app: safaricom-nginx-app
  template:
    metadata:
      labels:
        app: safaricom-nginx-app
    spec:
      containers:
        - name: nginx-slim
          image: registry.k8s.io/nginx-slim:0.8
          ports:
            - name: nginx
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: safaricom-nginx-data
              mountPath: "./C/users/IE PC/desktop"
      volumes:
        - name: safaricom-nginx-data
          persistentVolumeClaim:
            claimName: safaricom-data-nginx-pvc
            
  imagePullSecrets:
    - name: regcred
